#!/bin/bash

NREP=10
OPTS="--benchmark_display_aggregates_only=true --benchmark_report_aggregates_only=true"
EXEC=

for NP in 1 2 4 8 16; do
 
	for OMP_NUM_THREADS in 1 2 4 8; do
	
		NTOT=$(($NP * $OMP_NUM_THREADS))
		if [ "$NTOT" -lt "56" ]; then

			echo ""
			echo "===="
			echo "====  NP : $NP - OMP $OMP_NUM_THREADS | $NTOT "
			echo "===="
			echo ""

			outfile="elmpi_np${NP}_omp${OMP_NUM_THREADS}.out"
			mpirun -n $NP ${EXEC} --benchmark_out=${outfile} --benchmark_repetitions=${NREP} ${OPTS}
			
		fi
	done
done


